### ISSUE TITLE
chore: Refactor data generation logic

### ISSUE THREAD

**Issue by tikikun** [janhq/llama3-s#4]
Curren generation logic is utterly confused, need somewhat structure to reason through the generation pipeline + to be clear and concise about our synthetic data generation process

```
generation_pipeline.py

...

## convert text dataset into sound file for question
text_to_soundfine()

## convert soundfile to tokens
soundfile_to_tokens()

## mapping
....

## upload
```

**Comment by hungphongtrn** [comment]
![image](https://github.com/user-attachments/assets/73e63ff9-2c8d-42ef-8a2f-2c7163285994)
